# Generated by Django 6.1 on 2026-08-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250, verbose_name='نام و نام\u200cخانوادگی')),
                ('email', models.EmailField(max_length=250, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=15, verbose_name='شماره موبایل')),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'تماس با ما',
                'verbose_name_plural': 'تماس ها',
                'ordering': ['id'],
            },
        ),
    ]
